language: ruby
rvm:
  - 2.1.0

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.yml.sample config/database.yml
  - cp config/initializers/hosting.rb.example config/initializers/hosting.rb

script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake spec
